### ISSUE TITLE
下游任务处理

### ISSUE THREAD

**Issue by 1633232731** [CSHaitao/SAILER#3]
请问您是用dense作为下游任务的模型么？
我使用您的模型并使用dense.driver.encode 编码后
使用 dense.faiss_retriever 检索
在LeCaRD任务上的NDCG30只能得到 0.0823 
请问有可能是什么问题呢？
感谢

**Comment by CSHaitao** [comment]
可能是实现有错误？lecard加载中文模型，然后lecard是对每个查询有100个候选文档

**Comment by 1633232731** [comment]
多谢，解决了
我之前以为是对所有文档查询

**Comment by MurraryZhao** [comment]
> 多谢，解决了 我之前以为是对所有文档查询

你好，萌新想请问下怎么指定候选文档encode和retriever。
